#!/usr/bin/php
<?php
$city="Brooklyn";
$state="NY";
$country="US";
$url="http://api.openweathermap.org/data/2.5/weather?q=".$city.",".$country."&units=metric&cnt=7&lang=en";
$json=file_get_contents($url);
$data=json_decode($json,true);
//Get current Temperature in Celsius
echo $data['main']['temp']." ";
//Get weather condition
echo $data['weather'][0]['main']." ";
//Get cloud percentage
echo $data['clouds']['all']." ";
//Get wind speed
echo $data['wind']['speed']." ";

